version: "3.1"
services:
  logiconnect-nginx:
    container_name: history-nginx
    build: docker/nginx
    working_dir: /application
    restart: on-failure
    volumes:
      - .:/application:cached
      - ./var/nginx_logs:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/.ssh/:/root/.ssh/
    labels:
      - traefik.http.routers.history-nginx.rule=Host(`history.box`)

  logiconnect-fpm:
    container_name: history-fpm
    build: docker/php-fpm
    working_dir: /application
    restart: on-failure
    volumes:
      - .:/application:cached
      - ./var/log:/application/var/log
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      - ./docker/php-fpm/supervisord.conf:/etc/supervisord.conf
      - ~/.ssh/:/root/.ssh/
    labels:
      - traefik.enable=false

networks:
  default:
    external:
      name: nirvana