version: "3.1"
services:
  project-nginx:
      container_name: project-nginx
      build: docker/nginx
      working_dir: /application
      restart: on-failure
      volumes:
        - .:/application:cached
        - ./var/nginx_logs:/var/log/nginx
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ~/.ssh/:/root/.ssh/
      labels:
            - traefik.http.routers.project-nginx.rule=Host(`project.box`)

    project-fpm:
      container_name: project-fpm
      build: docker/php-fpm
      working_dir: /application
      restart: on-failure
      volumes:
        - .:/application:cached
        - ./var/log:/application/var/log
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ~/.ssh/:/root/.ssh/
      labels:
        - traefik.enable=false

networks:
  default:
    external:
      name: nirvana
